### ISSUE TITLE
Process ecospold2 to zolca or ilcd

### ISSUE THREAD

**Issue by SFrav** [msrocka/spold2#1]
Hi Michael,

Thanks for making this resource open source. 

Could you advise what the ecospold2 files are being processed to in this package? Is it to individual xml files or to a database (zolca or ilcd)?

**Comment by msrocka** [comment]
@SFrav this is just a library for reading and writing EcoSpold 2 data sets; it is not a converter. For importing/converting EcoSpold 2 files into an openLCA database or ILCD package (via an openLCA database) you could use the io module of the olca-modules: https://github.com/GreenDelta/olca-modules/tree/master/olca-io

**Comment by SFrav** [comment]
Thank you!
